package helpers.api.dolibarr.model.clientInvoice;

import java.math.BigDecimal;
import java.util.*;

/**
 * @author jtremeaux
 */
public class ClientInvoiceModel {
    public Integer socid;
    public Integer fk_user_author;
    public Integer fk_user_valid;
    public Date date;
    public Date datem;
    public String ref_client;
    public String type;
    public BigDecimal remise_absolue;
    public BigDecimal remise_percent;
    public BigDecimal total_ht;
    public BigDecimal total_tva;
    public BigDecimal total_localtax1;
    public BigDecimal total_localtax2;
    public BigDecimal total_ttc;
    public BigDecimal revenuestamp;
    public String close_code;
    public String close_note;
    public Integer paye;
    public String module_source;
    public String pos_source;
    public Integer fk_fac_rec_source;
    public Integer fk_facture_source;
    public List<String> linked_objects = new ArrayList<>();
    public Date date_lim_reglement;
    public String cond_reglement_code;
    public String mode_reglement_code;
    public Integer fk_bank;
    public List<Object> products = new ArrayList<>();
    public List<ClientInvoiceLineModel> lines = new ArrayList<>();
    public String line;
    public List<String> extraparams = new ArrayList<>();
    public String specimen;
    public String fac_rec;
    public Integer fk_multicurrency;
    public String multicurrency_code;
    public BigDecimal multicurrency_tx;
    public BigDecimal multicurrency_total_ht;
    public BigDecimal multicurrency_total_tva;
    public BigDecimal multicurrency_total_ttc;
    public String situation_cycle_ref;
    public String situation_counter;
    public Integer situation_final;
    public List<String> tab_previous_situation_invoice = new ArrayList<>();
    public List<String> tab_next_situation_invoice = new ArrayList<>();
    public String retained_warranty;
    public String retained_warrantyDate_limit;
    public Integer retained_warranty_fk_cond_reglement;
    public Integer id;
    public String import_key;
    public List<String> array_options = new ArrayList<>();
    public String linkedStrings_ids;
    public String canvas;
    public Integer fk_project;
    public String contact;
    public Integer contact_id;
    public String thirdparty;
    public String user;
    public String origin;
    public Integer origin_id;
    public String ref;
    public String ref_ext;
    public String statut;
    public String country;
    public Integer country_id;
    public String country_code;
    public String state;
    public Integer state_id;
    public String state_code;
    public Integer mode_reglement_id;
    public Integer cond_reglement_id;
    public String cond_reglement;
    public Integer shipping_method_id;
    public String modelpdf;
    public String last_main_doc;
    public Integer fk_account;
    public String note_public;
    public String note_private;
    public Integer fk_incoterms;
    public String label_incoterms;
    public String location_incoterms;
    public String name;
    public String lastname;
    public String firstname;
    public Integer civility_id;
    public Date date_creation;
    public Date date_validation;
    public Date date_modification;
    public Integer entity;
    public String date_pointoftax;
    public String mode_reglement;
    public String cond_reglement_doc;
    public Integer user_author;
    public Integer user_valid;
    public BigDecimal totalpaid;
    public BigDecimal totalcreditnotes;
    public BigDecimal totaldeposits;
    public BigDecimal remaintopay;
    public List<Integer> contacts_ids = new ArrayList<>();
    private Map<String, String> additional_properties = new HashMap<>();
}
